upload_material:
  summary: 上传素材
  tags:
    - yaml
  parameters:
    - name: file
      in: formData
      description: 待上传的文件
      required: true
      type: file
    - name: type
      in: formData
      description: 类型,image/voice/video/thumb
      type: string
      required: true
  consumes:
    - multipart/form-data
  responses:
    200:
      schema:
        properties:
          result:
            description: 错误码，默认0，成功
            type: integer
          message:
            description: 错误内容，默认OK
            type: string
get_material:
  summary: 获取素材
  tags:
    - yaml
  parameters:
    - in: query
      name: media_id
      type: string
  produces:
    - image/png
    - image/jpg
    - image/jpeg
    - image/gif
  responses:
    200:
      type: file
qrcode:
  summary: 生成二维码
  tags:
    - yaml
  parameters:
    - in: query
      name: content
      type: string
      required: true
  produces:
    - image/png
    - image/jpg
    - image/jpeg
    - image/gif
  responses:
    200:
      type: file